import { v4 as uuidv4 } from 'uuid';

export const products = [
  {
    id: uuidv4(),
    image: 'https://m.media-amazon.com/images/I/81PRtjUT5iL._SX712_.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: '2',
    image: 'https://m.media-amazon.com/images/I/71mu6crn-ZL._SX712_.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
    detail: `Lanvin Men's Footwear Size Chart Lanvin™ Wrap Concerto Chain Bag detachable chain link shoulder strap. Magnetic closure. Interior zipper pocket. Two interior slip pockets. Twelve credit card slots. Materials: Main: leather; Lining: leather and textile. Dust bag included. Made in Italy.`,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
];
