import { v4 as uuidv4 } from 'uuid';

export const products = [
  {
    id: uuidv4(),
    image: 'https://m.media-amazon.com/images/I/81PRtjUT5iL._SX712_.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
    {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending1.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending2.jpg',
    name: 'Paul Smile',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending3.jpg',
    name: 'Trending 3',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
  {
    id: uuidv4(),
    image: '/src/assets/images/trending4.jpg',
    name: 'Trending 4',
    title: 'Short sleeve Bloswing',
    price: 2900,
  },
];
